language: bash
services: docker

env:
  - VERSION=7.2 VARIANT=stretch/fpm
  - VERSION=7.1 VARIANT=stretch/fpm

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - slash='/'; image="php:${VERSION}-${VARIANT//$slash/-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" --build-arg BUILD_TAG="$image" .
    )
after_script:
  - docker images
