language: bash
services: docker

env:
  - VERSION=7.2 VARIANT=stretch/fpm
  - VERSION=7.1 VARIANT=stretch/fpm

install:
  - echo "skip"

before_script:
  - env | sort
  - cd "${VERSION}/${VARIANT}"
  - slash='/'; image="${DOCKER_REPO}:${VERSION}-${VARIANT//$slash/-}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" --build-arg BUILD_TAG="$image" .
    )
after_script:
  - docker images

deploy:
- provider: script
  script: >- 
   docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
   && docker push $image
