apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: k8s-test
  namespace: default
  labels: 
      name: k8s-test
      keel.sh/policy: major
      keel.sh/triggerr: poll
spec:
  replicas: 2
  template:
    metadata:
      name: k8s-test
      labels:
        app: k8s-test 
    spec:
      containers:                    
        - image: pristtlt/k8s-test:0.0.1
          imagePullPolicy: Always 
          name: wd
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
    name: k8s-test
    namespace: default
    labels:
        app: k8s-test
spec:
    type: NodePort
    ports:
        - name: k8s-test
          targetPort: 80
          protocol: TCP
          port: 80
    selector:
        app: k8s-test
    sessionAffinity: None
